In [ ]:
import pandas as pd
df=pd.read_csv("student_performance.csv")
df.head()
df.head(15)

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
10,1011,Vikram Iyer,20,Male,Electronics,2,80,75,68,72,83,Chennai,2023
11,1012,Pooja Gupta,19,Female,Civil,2,67,72,79,44,80,Jaipur,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78,82,51,91,Thrissur,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023

In [ ]:
df.shape

(30, 13)

In [ ]:
df.shape[0]

30

In [ ]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [ ]:
print(df.columns.tolist())

['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [ ]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [ ]:
df.isnull()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
print(df['department'].unique())

['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [ ]:
print(df['department'].value_counts())

department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [ ]:
print(df['gender'].value_counts())

gender
Male      15
Female    15
Name: count, dtype: int64

In [ ]:
print(df['city'].value_counts())

city
Kochi                 2
Lucknow               2
Thiruvananthapuram    2
Agra                  2
Kolkata               2
Hyderabad             1
Mumbai                1
Delhi                 1
Ahmedabad             1
Varanasi              1
Bangalore             1
Pune                  1
Jaipur                1
Mysore                1
Thrissur              1
Bhopal                1
Chennai               1
Patna                 1
Nagpur                1
Dehradun              1
Chandigarh            1
Surat                 1
Allahabad             1
Kanpur                1
Indore                1
Name: count, dtype: int64

In [ ]:
c=df[df['department']=='Electronics']
print(len(c))

6

In [ ]:
s_student = df[(df['city'] == 'Chennai') | (df['city'] == 'Mumbai')]
display(s_student[['name', 'city', 'math_score', 'science_score', 'english_score', 'programming_score']])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
s_student=df[(df['city']=='Chennai')|(df['city']=='Mumbai')]
print(s_student[['name','city','programming_score']])

            name     city  programming_score
0   Aarav Sharma   Mumbai                 91
10   Vikram Iyer  Chennai                 72

In [ ]:
df['total']=df['math_score']+df['english_score']+df['programming_score']+df['science_score']
top=df.loc[df['total'].idxmax()]
print(top)
min=df.loc[df['total'].idxmin()]
print(min)

student_id                           1010
name                           Ananya Das
age                                    19
gender                             Female
department               Computer Science
semester                                2
math_score                             95
science_score                          89
english_score                          90
programming_score                      97
attendance_percentage                  98
city                              Kolkata
admission_year                       2023
total                                 371
Name: 9, dtype: object
student_id                       1017
name                     Manoj Pandey
age                                21
gender                           Male
department                      Civil
semester                            2
math_score                         56
science_score                      61
english_score                      55
programming_score                  38
attendance_percentage              65
city                            Patna
admission_year                   2023
total                             210
Name: 16, dtype: object